create view `view_charges` (
  `banquet_charge_id`,
  `reservation_id`,
  `date`,
  `branch`,
  `detail_number`,
  `reservation_name`,
  `main_room_id`,
  `package_category`,
  `package_cat_name`,
  `package_id`,
  `package_name`,
  `item_group_id`,
  `item_group_name`,
  `item_id`,
  `item_name`,
  `item_gene_id`,
  `meal`,
  `drink1`,
  `drink2`,
  `unit_price`,
  `qty`,
  `amount_gross`,
  `amount_net`,
  `service_fee`,
  `tax`,
  `discount_name`,
  `discount_rate`,
  `discount_amount`
) as
select C.banquet_charge_id,
       C.reservation_id,
       C.date,
       C.branch,
       C.detail_number,
       C.reservation_name,
       C.main_room_id,
       C.package_category,
       C.package_cat_name,
       C.package_id,
       C.package_name,
       C.item_group_id,
       C.item_group_name,
       C.item_id,
       C.item_name,
       C.item_gene_id,
       I.meal,
       I.drink1,
       I.drink2,
       C.unit_price,
       C.qty,
       C.amount_gross,
       C.amount_net,
       C.service_fee,
       C.tax,
       C.discount_name,
       C.discount_rate,
       C.discount_amount
  from `banquet_charges` as C
  left join `banquet_items` as I
    on C.item_gene_id = I.banquet_item_id;