CREATE VIEW `view_monthly_new_reservation` AS
with `ranked_reservations` as (
  select 
    `pre_monthly_reservation_subtotal`.`sche_id` AS `sche_id`,
    `pre_monthly_reservation_subtotal`.`status` AS `status`,
    `pre_monthly_reservation_subtotal`.`status_name` AS `status_name`,
    `pre_monthly_reservation_subtotal`.`reservation_id` AS `reservation_id`,
    `pre_monthly_reservation_subtotal`.`reservation_name` AS `reservation_name`,
    `pre_monthly_reservation_subtotal`.`reservation_date` AS `reservation_date`,
    `pre_monthly_reservation_subtotal`.`cancel_date` AS `cancel_date`,
    `pre_monthly_reservation_subtotal`.`due_date` AS `due_date`,
    `pre_monthly_reservation_subtotal`.`d_created` AS `d_created`,
    `pre_monthly_reservation_subtotal`.`d_decided` AS `d_decided`,
    `pre_monthly_reservation_subtotal`.`d_tentative` AS `d_tentative`,
    `pre_monthly_reservation_subtotal`.`branch` AS `branch`,
    `pre_monthly_reservation_subtotal`.`count` AS `count`,
    `pre_monthly_reservation_subtotal`.`date` AS `date`,
    `pre_monthly_reservation_subtotal`.`room_id` AS `room_id`,
    `pre_monthly_reservation_subtotal`.`room_name` AS `room_name`,
    `pre_monthly_reservation_subtotal`.`people` AS `people`,
    `pre_monthly_reservation_subtotal`.`subtotal` AS `subtotal`,
    `pre_monthly_reservation_subtotal`.`gross` AS `gross`,
    `pre_monthly_reservation_subtotal`.`net` AS `net`,
    `pre_monthly_reservation_subtotal`.`service_fee` AS `service_fee`,
    `pre_monthly_reservation_subtotal`.`tax` AS `tax`,
    `pre_monthly_reservation_subtotal`.`discount` AS `discount`,
    `pre_monthly_reservation_subtotal`.`ex-ts` AS `ex-ts`,
    `pre_monthly_reservation_subtotal`.`purpose_id` AS `purpose_id`,
    `pre_monthly_reservation_subtotal`.`purpose_name` AS `purpose_name`,
    `pre_monthly_reservation_subtotal`.`purpose_short` AS `purpose_short`,
    `pre_monthly_reservation_subtotal`.`banquet_category_id` AS `banquet_category_id`,
    `pre_monthly_reservation_subtotal`.`banquet_category_name` AS `banquet_category_name`,
    `pre_monthly_reservation_subtotal`.`sales_dept_id` AS `sales_dept_id`,
    `pre_monthly_reservation_subtotal`.`sales_dept_name2` AS `sales_dept_name`,
    `pre_monthly_reservation_subtotal`.`sales_dept_short` AS `sales_dept_short`,
    `pre_monthly_reservation_subtotal`.`sales_category_id` AS `sales_category_id`,
    `pre_monthly_reservation_subtotal`.`sales_category_name` AS `sales_category_name`,
    `pre_monthly_reservation_subtotal`.`pic` AS `pic`,
    `pre_monthly_reservation_subtotal`.`pic_id` AS `pic_id`,
    `pre_monthly_reservation_subtotal`.`agent_id` AS `agent_id`,
    `pre_monthly_reservation_subtotal`.`agent_name` AS `agent_name`,
    `pre_monthly_reservation_subtotal`.`agent_short` AS `agent_short`,
    `pre_monthly_reservation_subtotal`.`agent_name2` AS `agent_name2`,
    `pre_monthly_reservation_subtotal`.`reserver` AS `reserver`,
    row_number() OVER (
      PARTITION BY `pre_monthly_reservation_subtotal`.`date`,`pre_monthly_reservation_subtotal`.`room_id` 
      ORDER BY `pre_monthly_reservation_subtotal`.`gross` desc 
    )  AS `rn` 
  from `pre_monthly_reservation_subtotal`
) 
select 
  `t1`.`sche_id` AS `sche_id`,
  `t1`.`status` AS `status`,
  `t1`.`status_name` AS `status_name`,
  `t1`.`date` AS `date`,
  `t1`.`room_id` AS `room_id`,
  `t2`.`reservation_id` AS `reservation_id`,
  `t2`.`reservation_date` AS `reservation_date`,
  `t2`.`cancel_date` AS `cancel_date`,
  `t2`.`due_date` AS `due_date`,
  `t2`.`d_created` AS `d_created`,
  `t2`.`d_decided` AS `d_decided`,
  `t2`.`d_tentative` AS `d_tentative`,
  `t2`.`branch` AS `branch`,
  `t2`.`reservation_name` AS `reservation_name`,
  `t2`.`room_name` AS `room_name`,
  `t2`.`banquet_category_id` AS `banquet_category_id`,
  `t2`.`banquet_category_name` AS `banquet_category_name`,
  `t2`.`sales_dept_id` AS `sales_dept_id`,
  `t2`.`sales_dept_name` AS `sales_dept_name`,
  `t2`.`sales_dept_short` AS `sales_dept_short`,
  `t2`.`sales_category_id` AS `sales_category_id`,
  `t2`.`sales_category_name` AS `sales_category_name`,
  `t2`.`people` AS `people`,
  `t2`.`purpose_id` AS `purpose_id`,
  `t2`.`purpose_name` AS `purpose_name`,
  `t2`.`purpose_short` AS `purpose_short`,
  sum(`t1`.`subtotal`) AS `subtotal`,
  sum(`t1`.`gross`) AS `gross`,
  sum(`t1`.`net`) AS `net`,
  sum(`t1`.`service_fee`) AS `service_fee`,
  sum(`t1`.`tax`) AS `tax`,
  sum(`t1`.`discount`) AS `discount`,
  sum(`t1`.`ex-ts`) AS `ex-ts`,
  `t2`.`pic` AS `pic`,
  `t2`.`pic_id` AS `pic_id`,
  `t2`.`agent_id` AS `agent_id`,
  `t2`.`agent_name` AS `agent_name`,
  `t2`.`agent_short` AS `agent_short`,
  `t2`.`agent_name2` AS `agent_name2`,
  `t2`.`reserver` AS `reserver` 
from (
  `pre_monthly_reservation_subtotal` `t1` join (
    select `ranked_reservations`.`sche_id` AS `sche_id`,
      `ranked_reservations`.`status` AS `status`,
      `ranked_reservations`.`status_name` AS `status_name`,
      `ranked_reservations`.`reservation_id` AS `reservation_id`,
      `ranked_reservations`.`reservation_name` AS `reservation_name`,
      `ranked_reservations`.`reservation_date` AS `reservation_date`,
      `ranked_reservations`.`cancel_date` AS `cancel_date`,
      `ranked_reservations`.`due_date` AS `due_date`,
      `ranked_reservations`.`d_created` AS `d_created`,
      `ranked_reservations`.`d_decided` AS `d_decided`,
      `ranked_reservations`.`d_tentative` AS `d_tentative`,
      `ranked_reservations`.`branch` AS `branch`,
      `ranked_reservations`.`count` AS `count`,
      `ranked_reservations`.`date` AS `date`,
      `ranked_reservations`.`room_id` AS `room_id`,
      `ranked_reservations`.`room_name` AS `room_name`,
      `ranked_reservations`.`purpose_id` AS `purpose_id`,
      `ranked_reservations`.`purpose_name` AS `purpose_name`,
      `ranked_reservations`.`purpose_short` AS `purpose_short`,
      `ranked_reservations`.`people` AS `people`,
      `ranked_reservations`.`subtotal` AS `subtotal`,
      `ranked_reservations`.`gross` AS `gross`,
      `ranked_reservations`.`net` AS `net`,
      `ranked_reservations`.`service_fee` AS `service_fee`,
      `ranked_reservations`.`tax` AS `tax`,
      `ranked_reservations`.`discount` AS `discount`,
      `ranked_reservations`.`ex-ts` AS `ex-ts`,
      `ranked_reservations`.`banquet_category_id` AS `banquet_category_id`,
      `ranked_reservations`.`banquet_category_name` AS `banquet_category_name`,
      `ranked_reservations`.`sales_dept_id` AS `sales_dept_id`,
      `ranked_reservations`.`sales_dept_name` AS `sales_dept_name`,
      `ranked_reservations`.`sales_dept_short` AS `sales_dept_short`,
      `ranked_reservations`.`sales_category_id` AS `sales_category_id`,
      `ranked_reservations`.`sales_category_name` AS `sales_category_name`,
      `ranked_reservations`.`pic` AS `pic`,
      `ranked_reservations`.`pic_id` AS `pic_id`,
      `ranked_reservations`.`agent_id` AS `agent_id`,
      `ranked_reservations`.`agent_name` AS `agent_name`,
      `ranked_reservations`.`agent_short` AS `agent_short`,
      `ranked_reservations`.`agent_name2` AS `agent_name2`,
      `ranked_reservations`.`reserver` AS `reserver`,
      `ranked_reservations`.`rn` AS `rn` 
    from `ranked_reservations` 
    where (`ranked_reservations`.`rn` = 1)
  ) `t2` on(
    (
      (`t1`.`date` = `t2`.`date`) 
      and (`t1`.`room_id` = `t2`.`room_id`)
      and (`t1`.`reservation_id` = `t2`.`reservation_id`)
    )
  )
) 
group by
`t1`.`status`,
`t1`.`date`,
`t1`.`room_id`