CREATE VIEW `view_monthly_new_reservation3` AS
with `ranked_reservations` as (
  select
    `p`.`sche_id` AS `sche_id`,
    `p`.`status` AS `status`,
    `p`.`status_name` AS `status_name`,
    `p`.`reservation_id` AS `reservation_id`,
    `p`.`reservation_name` AS `reservation_name`,
    `p`.`reservation_date` AS `reservation_date`,
    `p`.`cancel_date` AS `cancel_date`,
    `p`.`due_date` AS `due_date`,
    `p`.`d_created` AS `d_created`,
    `p`.`d_decided` AS `d_decided`,
    `p`.`d_tentative` AS `d_tentative`,
    `p`.`branch` AS `branch`,
    `p`.`count` AS `count`,
    `p`.`date` AS `date`,
    `p`.`room_id` AS `room_id`,
    `p`.`room_name` AS `room_name`,
    `p`.`people` AS `people`,
    `p`.`subtotal` AS `subtotal`,
    `p`.`gross` AS `gross`,
    `p`.`net` AS `net`,
    `p`.`service_fee` AS `service_fee`,
    `p`.`tax` AS `tax`,
    `p`.`discount` AS `discount`,
    `p`.`ex_ts` AS `ex_ts`,
    `p`.`purpose_id` AS `purpose_id`,
    `p`.`purpose_name` AS `purpose_name`,
    `p`.`purpose_short` AS `purpose_short`,
    `p`.`banquet_category_id` AS `banquet_category_id`,
    `p`.`banquet_category_name` AS `banquet_category_name`,
    `p`.`sales_dept_id` AS `sales_dept_id`,
    `p`.`sales_dept_name2` AS `sales_dept_name`,
    `p`.`sales_dept_short` AS `sales_dept_short`,
    `p`.`sales_category_id` AS `sales_category_id`,
    `p`.`sales_category_name` AS `sales_category_name`,
    `p`.`reservation_type_code` AS `reservation_type_code`,
    `p`.`reservation_type` AS `reservation_type`,
    `p`.`reservation_type_name` AS `reservation_type_name`,
    `p`.`pic` AS `pic`,
    `p`.`pic_id` AS `pic_id`,
    `p`.`agent_id` AS `agent_id`,
    `p`.`agent_name` AS `agent_name`,
    `p`.`agent_short` AS `agent_short`,
    `p`.`agent_name2` AS `agent_name2`,
    `p`.`reserver` AS `reserver`,
    `p`.`memo` AS `memo`,
    row_number() OVER (
      PARTITION BY `p`.`date`,
      `p`.`room_id`,
      `p`.`reservation_id` ORDER BY `p`.`gross` desc,
      `p`.`net` desc,
      `p`.`sche_id` desc
    ) AS `rn`
  from `pre_monthly_reservation_subtotal3` `p`
),
`top_res` as (
  select
    `ranked_reservations`.`sche_id` AS `sche_id`,
    `ranked_reservations`.`status` AS `status`,
    `ranked_reservations`.`status_name` AS `status_name`,
    `ranked_reservations`.`reservation_id` AS `reservation_id`,
    `ranked_reservations`.`reservation_name` AS `reservation_name`,
    `ranked_reservations`.`reservation_date` AS `reservation_date`,
    `ranked_reservations`.`cancel_date` AS `cancel_date`,
    `ranked_reservations`.`due_date` AS `due_date`,
    `ranked_reservations`.`d_created` AS `d_created`,
    `ranked_reservations`.`d_decided` AS `d_decided`,
    `ranked_reservations`.`d_tentative` AS `d_tentative`,
    `ranked_reservations`.`branch` AS `branch`,
    `ranked_reservations`.`count` AS `count`,
    `ranked_reservations`.`date` AS `date`,
    `ranked_reservations`.`room_id` AS `room_id`,
    `ranked_reservations`.`room_name` AS `room_name`,
    `ranked_reservations`.`people` AS `people`,
    `ranked_reservations`.`subtotal` AS `subtotal`,
    `ranked_reservations`.`gross` AS `gross`,
    `ranked_reservations`.`net` AS `net`,
    `ranked_reservations`.`service_fee` AS `service_fee`,
    `ranked_reservations`.`tax` AS `tax`,
    `ranked_reservations`.`discount` AS `discount`,
    `ranked_reservations`.`ex_ts` AS `ex_ts`,
    `ranked_reservations`.`purpose_id` AS `purpose_id`,
    `ranked_reservations`.`purpose_name` AS `purpose_name`,
    `ranked_reservations`.`purpose_short` AS `purpose_short`,
    `ranked_reservations`.`banquet_category_id` AS `banquet_category_id`,
    `ranked_reservations`.`banquet_category_name` AS `banquet_category_name`,
    `ranked_reservations`.`sales_dept_id` AS `sales_dept_id`,
    `ranked_reservations`.`sales_dept_name` AS `sales_dept_name`,
    `ranked_reservations`.`sales_dept_short` AS `sales_dept_short`,
    `ranked_reservations`.`sales_category_id` AS `sales_category_id`,
    `ranked_reservations`.`sales_category_name` AS `sales_category_name`,
    `ranked_reservations`.`reservation_type_code` AS `reservation_type_code`,
    `ranked_reservations`.`reservation_type` AS `reservation_type`,
    `ranked_reservations`.`reservation_type_name` AS `reservation_type_name`,
    `ranked_reservations`.`pic` AS `pic`,
    `ranked_reservations`.`pic_id` AS `pic_id`,
    `ranked_reservations`.`agent_id` AS `agent_id`,
    `ranked_reservations`.`agent_name` AS `agent_name`,
    `ranked_reservations`.`agent_short` AS `agent_short`,
    `ranked_reservations`.`agent_name2` AS `agent_name2`,
    `ranked_reservations`.`reserver` AS `reserver`,
    `ranked_reservations`.`memo` AS `memo`
  from `ranked_reservations`
  where (`ranked_reservations`.`rn` = 1)
),
`agg` as (
  select
    `t1`.`date` AS `date`,
    `t1`.`room_id` AS `room_id`,
    `t1`.`reservation_id` AS `reservation_id`,
    sum(`t1`.`subtotal`) AS `subtotal`,
    sum(`t1`.`gross`) AS `gross`,
    sum(`t1`.`net`) AS `net`,
    sum(`t1`.`service_fee`) AS `service_fee`,
    sum(`t1`.`tax`) AS `tax`,
    sum(`t1`.`discount`) AS `discount`,
    sum(`t1`.`ex_ts`) AS `ex_ts`
  from `pre_monthly_reservation_subtotal3` `t1`
  group by `t1`.`date`,
    `t1`.`room_id`,
    `t1`.`reservation_id`) 
    select
    `tr`.`status` AS `status`,
    `tr`.`status_name` AS `status_name`,
    `a`.`date` AS `date`,
    `a`.`room_id` AS `room_id`,
    `tr`.`sche_id` AS `sche_id`,
    `tr`.`reservation_id` AS `reservation_id`,
    `tr`.`reservation_date` AS `reservation_date`,
    `tr`.`cancel_date` AS `cancel_date`,
    `tr`.`due_date` AS `due_date`,
    `tr`.`d_created` AS `d_created`,
    `tr`.`d_decided` AS `d_decided`,
    `tr`.`d_tentative` AS `d_tentative`,
    `tr`.`branch` AS `branch`,
    `tr`.`reservation_name` AS `reservation_name`,
    `tr`.`room_name` AS `room_name`,
    `tr`.`banquet_category_id` AS `banquet_category_id`,
    `tr`.`banquet_category_name` AS `banquet_category_name`,
    `tr`.`sales_dept_id` AS `sales_dept_id`,
    `tr`.`sales_dept_name` AS `sales_dept_name`,
    `tr`.`sales_dept_short` AS `sales_dept_short`,
    `tr`.`sales_category_id` AS `sales_category_id`,
    `tr`.`sales_category_name` AS `sales_category_name`,
    `tr`.`reservation_type_code` AS `reservation_type_code`,
    `tr`.`reservation_type` AS `reservation_type`,
    `tr`.`reservation_type_name` AS `reservation_type_name`,
    `tr`.`people` AS `people`,
    `tr`.`purpose_id` AS `purpose_id`,
    `tr`.`purpose_name` AS `purpose_name`,
    `tr`.`purpose_short` AS `purpose_short`,
    `a`.`subtotal` AS `subtotal`,
    `a`.`gross` AS `gross`,
    `a`.`net` AS `net`,
    `a`.`service_fee` AS `service_fee`,
    `a`.`tax` AS `tax`,
    `a`.`discount` AS `discount`,
    `a`.`ex_ts` AS `ex_ts`,
    `tr`.`pic` AS `pic`,
    `tr`.`pic_id` AS `pic_id`,
    `tr`.`agent_id` AS `agent_id`,
    `tr`.`agent_name` AS `agent_name`,
    `tr`.`agent_short` AS `agent_short`,
    `tr`.`agent_name2` AS `agent_name2`,
    `tr`.`reserver` AS `reserver`,
    `tr`.`memo` AS `memo`,
    CASE
    WHEN `tr`.`reservation_type` = `tr`.`sales_category_id` THEN 0
      ELSE 1
    END AS `reservation_sales_diff`,
    CASE
    WHEN `tr`.`due_date` < CURDATE() THEN 1
      ELSE 0
    END AS `due_over_flg`
    
  from `agg` `a`
    join `top_res` `tr`
      on `tr`.`date` = `a`.`date`
      and `tr`.`room_id` = `a`.`room_id`
      and `tr`.`reservation_id` = `a`.`reservation_id`
  